require("core.keymaps")
require("core.plugins")
require("core.plugin_config")

vim.api.nvim_command('set nu')
vim.api.nvim_command('set rnu')
vim.api.nvim_command('set wrap')
vim.api.nvim_command('set linebreak')
vim.api.nvim_command('set nolist')
vim.api.nvim_command('set scrolloff=999')
vim.api.nvim_command('set smartcase')
vim.api.nvim_command('set ignorecase')
