#!/bin/bash
output=$HOME/Pictures/Screenshots/%Y-%m-%d-%T-screenshot.png

case "$1" in
  "-full") scrot "$output" || exit ;; 
  "-window") scrot "$output" --focused --border || exit ;;
  *) scrot "$output" --select --line mode=edge || exit ;;
esac

notify-send "Screenshot taken"
