#!/bin/sh

path="${1:-$HOME/Documents/todo}"

sed "/\[X\]/ d;
    /^$/ d;
    s/\[ \] /x\[ \]/;
    s/\[L\] /w\[L\]/; 
    s/\[W\] /y\[W\]/;
    s/\[I\] /z\[I\]/;
    /^\([0-9]\{4\}\) - \([0-9][0-9]\) - \([0-9][0-9]\).*$/ d
    " $path | sort | nl -w 3 -s ". " | sed "s/x\[ \]//;
    /w\[L\]/ s/\(^.*$\)/$(tput setaf 1)\1$(tput op)/;
    s/w\[L\]//;
    /y\[W\]/ s/\(^.*$\)/$(tput setaf 2)\1$(tput op)/;
    s/y\[W\]//;
    /z\[I\]/ s/\(^.*$\)/$(tput setaf 4)\1$(tput op)/;
    s/z\[I\]//;" 

