#!/bin/sh

path="${1:-$HOME/Documents/todo}"

sed "
    /\[X\]/ d;
    /^$/ d;
    s/\[ \] /a\[ \]/;
    s/\[W\] /b\[W\]/;
    s/\[I\] /c\[I\]/;
    /^\([0-9]\{4\}\) - \([0-9][0-9]\) - \([0-9][0-9]\)$/ d
    " $path | sort | sed "s/a\[ \]//" | nl -w 3 -s ". "

